/**
 * Constantes de Indicadores ISO 37120/37122/37123 + Marco de Sendai
 * Estrutura deverá ser enviada como ManualCityIndicators no backend  
 */

export const EMPTY_INDICATORS = {
  iso_37120: {
    taxa_desemprego_pct: 0,
    taxa_endividamento_pct: 0,
    despesas_capital_pct: 0,
    receita_propria_pct: 0,
    orcamento_per_capita: 0,
    mulheres_eleitas_pct: 0,
    condenacoes_corrupcao_100k: 0,
    participacao_eleitoral_pct: 0,
    moradias_inadequadas_pct: 0,
    sem_teto_100k: 0,
    bombeiros_100k: 0,
    mortes_incendio_100k: 0,
    agentes_policia_100k: 0,
    homicidios_100k: 0,
    acidentes_industriais_100k: 0,
  },
  iso_37122: {
    sobrevivencia_novos_negocios_100k: 0,
    empregos_tic_pct: 0,
    graduados_stem_100k: 0,
    energia_residuos_pct: 0,
    iluminacao_telegestao_pct: 0,
    medidores_inteligentes_energia_pct: 0,
    edificios_verdes_pct: 0,
    monitoramento_ar_tempo_real_pct: 0,
    servicos_urbanos_online_pct: 0,
    prontuario_eletronico_pct: 0,
    consultas_remotas_100k: 0,
    medidores_inteligentes_agua_pct: 0,
    areas_cobertas_cameras_pct: 0,
    lixeiras_sensores_pct: 0,
    semaforos_inteligentes_pct: 0,
    frota_onibus_limpos_pct: 0,
  },
  iso_37123: {
    seguro_ameacas_pct: 0,
    empregos_informais_pct: 0,
    escolas_preparacao_emergencia_pct: 0,
    populacao_treinada_emergencia_pct: 0,
    hospitais_geradores_backup_pct: 0,
    seguro_saude_basico_pct: 0,
    imunizacao_pct: 0,
    abrigos_emergencia_100k: 0,
    edificios_vulneraveis_pct: 0,
    rotas_evacuacao_100k: 0,
    reservas_alimentos_72h_pct: 0,
    mapas_ameacas_publicos_pct: 0,
    mortalidade_desastres_100k: 0,
    pessoas_afetadas_desastres_100k: 0,
    perdas_desastres_pct_pib: 0,
    danos_infraestrutura_basica_pct: 0,
  },
};

export const FIELD_DESCRIPTIONS = {
  iso_37120: {
    taxa_desemprego_pct: {
      label: "Taxa de Desemprego",
      unit: "%",
      placeholder: "0-100",
      help: "Percentual de população desempregada. MENOR é melhor",
    },
    taxa_endividamento_pct: {
      label: "Taxa de Endividamento",
      unit: "%",
      placeholder: "0-200",
      help: "Percentual de endividamento da prefeitura. MENOR é melhor",
    },
    despesas_capital_pct: {
      label: "Despesas de Capital",
      unit: "% orçamento",
      placeholder: "0-100",
      help: "Percentual do orçamento em investimentos. MAIOR é melhor",
    },
    receita_propria_pct: {
      label: "Receita Própria",
      unit: "% receita",
      placeholder: "0-100",
      help: "Percentual de receita própria (autonomia). MAIOR é melhor",
    },
    orcamento_per_capita: {
      label: "Orçamento per Capita",
      unit: "R$",
      placeholder: "0-10000",
      help: "Orçamento por habitante. MAIOR é melhor",
    },
    mulheres_eleitas_pct: {
      label: "Mulheres Eleitas",
      unit: "%",
      placeholder: "0-100",
      help: "Percentual de mulheres em cargos de gestão. MAIOR é melhor",
    },
    condenacoes_corrupcao_100k: {
      label: "Condenações por Corrupção",
      unit: "por 100k",
      placeholder: "0-100",
      help: "Taxa de condenações por corrupção. MENOR é melhor",
    },
    participacao_eleitoral_pct: {
      label: "Participação Eleitoral",
      unit: "%",
      placeholder: "0-100",
      help: "Taxa de participação em eleições. MAIOR é melhor",
    },
    moradias_inadequadas_pct: {
      label: "Moradias Inadequadas",
      unit: "% população",
      placeholder: "0-100",
      help: "Percentual de população em moradias inadequadas. MENOR é melhor",
    },
    sem_teto_100k: {
      label: "Sem-teto",
      unit: "por 100k",
      placeholder: "0-1000",
      help: "Taxa de população em situação de rua. MENOR é melhor",
    },
    bombeiros_100k: {
      label: "Bombeiros",
      unit: "por 100k hab",
      placeholder: "0-200",
      help: "Taxa de bombeiros disponíveis. MAIOR é melhor",
    },
    mortes_incendio_100k: {
      label: "Mortes por Incêndio",
      unit: "por 100k",
      placeholder: "0-50",
      help: "Taxa de mortes por incêndio. MENOR é melhor",
    },
    agentes_policia_100k: {
      label: "Agentes de Polícia",
      unit: "por 100k hab",
      placeholder: "0-1000",
      help: "Taxa de agentes policiais. MAIOR é melhor",
    },
    homicidios_100k: {
      label: "Homicídios",
      unit: "por 100k",
      placeholder: "0-100",
      help: "Taxa de homicídios. MENOR é melhor",
    },
    acidentes_industriais_100k: {
      label: "Acidentes Industriais",
      unit: "por 100k",
      placeholder: "0-50",
      help: "Taxa de acidentes industriais. MENOR é melhor",
    },
  },
  iso_37122: {
    sobrevivencia_novos_negocios_100k: {
      label: "Novos Negócios Viáveis",
      unit: "por 100k hab",
      placeholder: "0-500",
      help: "Negócios que sobrevivem 5+ anos. MAIOR é melhor",
    },
    empregos_tic_pct: {
      label: "Empregos em TIC",
      unit: "% força trabalho",
      placeholder: "0-50",
      help: "Percentual de empregos em TIC. MAIOR é melhor",
    },
    graduados_stem_100k: {
      label: "Graduados STEM",
      unit: "por 100k hab",
      placeholder: "0-5000",
      help: "Graduados em STEM (Science, Technology, Engineering, Math). MAIOR é melhor",
    },
    energia_residuos_pct: {
      label: "Energia de Resíduos",
      unit: "% total",
      placeholder: "0-100",
      help: "Percentual de energia vinda de resíduos (biomassa). MAIOR é melhor",
    },
    iluminacao_telegestao_pct: {
      label: "Iluminação Pública Inteligente",
      unit: "%",
      placeholder: "0-100",
      help: "Iluminação com telegestão. MAIOR é melhor",
    },
    medidores_inteligentes_energia_pct: {
      label: "Medidores Inteligentes Energia",
      unit: "%",
      placeholder: "0-100",
      help: "Casas com medidores inteligentes. MAIOR é melhor",
    },
    edificios_verdes_pct: {
      label: "Edifícios Verdes",
      unit: "%",
      placeholder: "0-100",
      help: "Edifícios com certificação verde. MAIOR é melhor",
    },
    monitoramento_ar_tempo_real_pct: {
      label: "Monitoramento de Ar",
      unit: "%",
      placeholder: "0-100",
      help: "Áreas com monitoramento de qualidade de ar real-time. MAIOR é melhor",
    },
    servicos_urbanos_online_pct: {
      label: "Serviços Urbanos Online",
      unit: "%",
      placeholder: "0-100",
      help: "Serviços da prefeitura disponíveis online. MAIOR é melhor",
    },
    prontuario_eletronico_pct: {
      label: "Prontuário Eletrônico",
      unit: "% população",
      placeholder: "0-100",
      help: "População com prontuário eletrônico. MAIOR é melhor",
    },
    consultas_remotas_100k: {
      label: "Consultas Remotas",
      unit: "por 100k hab",
      placeholder: "0-100000",
      help: "Consultas médicas remotas realizadas. MAIOR é melhor",
    },
    medidores_inteligentes_agua_pct: {
      label: "Medidores Inteligentes Água",
      unit: "%",
      placeholder: "0-100",
      help: "Casas com medidores inteligentes de água. MAIOR é melhor",
    },
    areas_cobertas_cameras_pct: {
      label: "Cobertura de Câmeras",
      unit: "% cidade",
      placeholder: "0-100",
      help: "Áreas da cidade cobertas por câmeras. MAIOR é melhor",
    },
    lixeiras_sensores_pct: {
      label: "Lixeiras Inteligentes",
      unit: "%",
      placeholder: "0-100",
      help: "Lixeiras com sensores de capacidade. MAIOR é melhor",
    },
    semaforos_inteligentes_pct: {
      label: "Semáforos Inteligentes",
      unit: "%",
      placeholder: "0-100",
      help: "Semáforos com sistema adaptativo. MAIOR é melhor",
    },
    frota_onibus_limpos_pct: {
      label: "Frota Ônibus Zero Emissão",
      unit: "%",
      placeholder: "0-100",
      help: "Ônibus com zero emissão de carbono. MAIOR é melhor",
    },
  },
  iso_37123: {
    seguro_ameacas_pct: {
      label: "População Segurada",
      unit: "%",
      placeholder: "0-100",
      help: "População coberta por seguro contra ameaças. MAIOR é melhor",
    },
    empregos_informais_pct: {
      label: "Empregos Informais",
      unit: "% força trabalho",
      placeholder: "0-100",
      help: "Percentual de empregos informais. MENOR é melhor",
    },
    escolas_preparacao_emergencia_pct: {
      label: "Escolas com Plano Emergência",
      unit: "%",
      placeholder: "0-100",
      help: "Escolas com plano de emergência. MAIOR é melhor",
    },
    populacao_treinada_emergencia_pct: {
      label: "População Treinada em Emergência",
      unit: "%",
      placeholder: "0-100",
      help: "População treinada em procedimentos de emergência. MAIOR é melhor",
    },
    hospitais_geradores_backup_pct: {
      label: "Hospitais com Gerador Backup",
      unit: "%",
      placeholder: "0-100",
      help: "Hospitais com gerador de energia de backup. MAIOR é melhor",
    },
    seguro_saude_basico_pct: {
      label: "Cobertura de Saúde Básica",
      unit: "%",
      placeholder: "0-100",
      help: "População com seguro saúde básico. MAIOR é melhor",
    },
    imunizacao_pct: {
      label: "Taxa de Imunização",
      unit: "%",
      placeholder: "0-100",
      help: "Taxa de imunização da população. MAIOR é melhor",
    },
    abrigos_emergencia_100k: {
      label: "Abrigos de Emergência",
      unit: "por 100k hab",
      placeholder: "0-50",
      help: "Abrigos destinados para emergências. MAIOR é melhor",
    },
    edificios_vulneraveis_pct: {
      label: "Edifícios Vulneráveis",
      unit: "%",
      placeholder: "0-100",
      help: "Edifícios vulneráveis a desastres. MENOR é melhor",
    },
    rotas_evacuacao_100k: {
      label: "Rotas de Evacuação Identificadas",
      unit: "por 100k",
      placeholder: "0-100",
      help: "Rotas de evacuação identificadas. MAIOR é melhor",
    },
    reservas_alimentos_72h_pct: {
      label: "Reservas de Alimentos 72h",
      unit: "%",
      placeholder: "0-100",
      help: "Cidades com reservas de alimentos para 72h. MAIOR é melhor",
    },
    mapas_ameacas_publicos_pct: {
      label: "Mapas de Ameaças Públicos",
      unit: "%",
      placeholder: "0-100",
      help: "Mapas de ameaças públicos e atualizados. MAIOR é melhor",
    },
    mortalidade_desastres_100k: {
      label: "Mortalidade por Desastres",
      unit: "por 100k hab",
      placeholder: "0-100",
      help: "Taxa de mortalidade por desastres naturais. MENOR é melhor",
    },
    pessoas_afetadas_desastres_100k: {
      label: "Pessoas Afetadas por Desastres",
      unit: "por 100k hab",
      placeholder: "0-10000",
      help: "Pessoas afetadas por desastres por 100k. MENOR é melhor",
    },
    perdas_desastres_pct_pib: {
      label: "Perdas por Desastres",
      unit: "% PIB",
      placeholder: "0-50",
      help: "Perdas econômicas por desastres em % do PIB. MENOR é melhor",
    },
    danos_infraestrutura_basica_pct: {
      label: "Danos à Infraestrutura Básica",
      unit: "%",
      placeholder: "0-100",
      help: "Infraestrutura básica prejudicada por desastres. MENOR é melhor",
    },
  },
};
