"""Refatoracao para 47 indicadores JSON

Revision ID: 87f0c665dac1
Revises: 
Create Date: 2026-04-01 11:51:51.944467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f0c665dac1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_manual_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.String(), nullable=False),
    sa.Column('nome_cidade', sa.String(), nullable=True),
    sa.Column('indicadores_manuais', sa.JSON(), nullable=True),
    sa.Column('fonte', sa.String(), nullable=True),
    sa.Column('usuario_atualizou', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_manual_data_codigo_ibge'), 'city_manual_data', ['codigo_ibge'], unique=True)
    op.create_index(op.f('ix_city_manual_data_id'), 'city_manual_data', ['id'], unique=False)
    op.create_table('indicadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_indicador', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('norma', sa.String(), nullable=True),
    sa.Column('grande_area', sa.String(), nullable=True),
    sa.Column('eixo', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicadores_codigo_indicador'), 'indicadores', ['codigo_indicador'], unique=True)
    op.create_index(op.f('ix_indicadores_id'), 'indicadores', ['id'], unique=False)
    op.create_table('ranking_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ranking_data', sa.JSON(), nullable=True),
    sa.Column('matriz_decisao', sa.JSON(), nullable=True),
    sa.Column('indicadores_nomes', sa.JSON(), nullable=True),
    sa.Column('pesos', sa.JSON(), nullable=True),
    sa.Column('impactos', sa.JSON(), nullable=True),
    sa.Column('data_calculo', sa.DateTime(), nullable=True),
    sa.Column('periodo_referencia', sa.String(), nullable=True),
    sa.Column('quantidade_cidades', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_snapshot_data_calculo'), 'ranking_snapshot', ['data_calculo'], unique=False)
    op.create_index(op.f('ix_ranking_snapshot_id'), 'ranking_snapshot', ['id'], unique=False)
    op.create_index(op.f('ix_ranking_snapshot_periodo_referencia'), 'ranking_snapshot', ['periodo_referencia'], unique=False)
    op.create_table('city_manual_data_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.String(), nullable=True),
    sa.Column('dados_antigos', sa.JSON(), nullable=True),
    sa.Column('dados_novos', sa.JSON(), nullable=True),
    sa.Column('alteracoes_resumo', sa.Text(), nullable=True),
    sa.Column('usuario_atualizou', sa.String(), nullable=True),
    sa.Column('motivo_atualizacao', sa.String(), nullable=True),
    sa.Column('data_alteracao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_ibge'], ['city_manual_data.codigo_ibge'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_manual_data_history_codigo_ibge'), 'city_manual_data_history', ['codigo_ibge'], unique=False)
    op.create_index(op.f('ix_city_manual_data_history_data_alteracao'), 'city_manual_data_history', ['data_alteracao'], unique=False)
    op.create_index(op.f('ix_city_manual_data_history_id'), 'city_manual_data_history', ['id'], unique=False)
    op.create_table('dados_coleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('ano_referencia', sa.Integer(), nullable=True),
    sa.Column('valor_numerador', sa.Float(), nullable=True),
    sa.Column('valor_denominador', sa.Float(), nullable=True),
    sa.Column('valor_final', sa.Float(), nullable=True),
    sa.Column('dado_disponivel', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dados_coleta_cidade'), 'dados_coleta', ['cidade'], unique=False)
    op.create_index(op.f('ix_dados_coleta_id'), 'dados_coleta', ['id'], unique=False)
    op.create_table('indicator_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_ibge', sa.String(), nullable=True),
    sa.Column('valores_indicadores', sa.JSON(), nullable=False),
    sa.Column('data_calculo', sa.DateTime(), nullable=True),
    sa.Column('fonte_dados', sa.String(), nullable=True),
    sa.Column('periodo_referencia', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_ibge'], ['city_manual_data.codigo_ibge'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_snapshot_codigo_ibge'), 'indicator_snapshot', ['codigo_ibge'], unique=False)
    op.create_index(op.f('ix_indicator_snapshot_data_calculo'), 'indicator_snapshot', ['data_calculo'], unique=False)
    op.create_index(op.f('ix_indicator_snapshot_id'), 'indicator_snapshot', ['id'], unique=False)
    op.create_table('metodologias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=True),
    sa.Column('desc_numerador', sa.Text(), nullable=True),
    sa.Column('desc_denominador', sa.Text(), nullable=True),
    sa.Column('multiplicador', sa.Float(), nullable=True),
    sa.Column('unidade_medida', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodologias_id'), 'metodologias', ['id'], unique=False)
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dados_coleta_id', sa.Integer(), nullable=True),
    sa.Column('fonte_nome', sa.String(), nullable=True),
    sa.Column('fonte_url', sa.String(), nullable=True),
    sa.Column('data_extracao', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dados_coleta_id'], ['dados_coleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorias_id'), 'auditorias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditorias_id'), table_name='auditorias')
    op.drop_table('auditorias')
    op.drop_index(op.f('ix_metodologias_id'), table_name='metodologias')
    op.drop_table('metodologias')
    op.drop_index(op.f('ix_indicator_snapshot_id'), table_name='indicator_snapshot')
    op.drop_index(op.f('ix_indicator_snapshot_data_calculo'), table_name='indicator_snapshot')
    op.drop_index(op.f('ix_indicator_snapshot_codigo_ibge'), table_name='indicator_snapshot')
    op.drop_table('indicator_snapshot')
    op.drop_index(op.f('ix_dados_coleta_id'), table_name='dados_coleta')
    op.drop_index(op.f('ix_dados_coleta_cidade'), table_name='dados_coleta')
    op.drop_table('dados_coleta')
    op.drop_index(op.f('ix_city_manual_data_history_id'), table_name='city_manual_data_history')
    op.drop_index(op.f('ix_city_manual_data_history_data_alteracao'), table_name='city_manual_data_history')
    op.drop_index(op.f('ix_city_manual_data_history_codigo_ibge'), table_name='city_manual_data_history')
    op.drop_table('city_manual_data_history')
    op.drop_index(op.f('ix_ranking_snapshot_periodo_referencia'), table_name='ranking_snapshot')
    op.drop_index(op.f('ix_ranking_snapshot_id'), table_name='ranking_snapshot')
    op.drop_index(op.f('ix_ranking_snapshot_data_calculo'), table_name='ranking_snapshot')
    op.drop_table('ranking_snapshot')
    op.drop_index(op.f('ix_indicadores_id'), table_name='indicadores')
    op.drop_index(op.f('ix_indicadores_codigo_indicador'), table_name='indicadores')
    op.drop_table('indicadores')
    op.drop_index(op.f('ix_city_manual_data_id'), table_name='city_manual_data')
    op.drop_index(op.f('ix_city_manual_data_codigo_ibge'), table_name='city_manual_data')
    op.drop_table('city_manual_data')
    # ### end Alembic commands ###
