"""Criação das tabelas iniciais

Revision ID: a62ea43bc525
Revises: 
Create Date: 2026-03-10 17:32:21.019936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62ea43bc525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_indicador', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('norma', sa.String(), nullable=True),
    sa.Column('grande_area', sa.String(), nullable=True),
    sa.Column('eixo', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicadores_codigo_indicador'), 'indicadores', ['codigo_indicador'], unique=True)
    op.create_index(op.f('ix_indicadores_id'), 'indicadores', ['id'], unique=False)
    op.create_table('dados_coleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('ano_referencia', sa.Integer(), nullable=True),
    sa.Column('valor_numerador', sa.Float(), nullable=True),
    sa.Column('valor_denominador', sa.Float(), nullable=True),
    sa.Column('valor_final', sa.Float(), nullable=True),
    sa.Column('dado_disponivel', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dados_coleta_cidade'), 'dados_coleta', ['cidade'], unique=False)
    op.create_index(op.f('ix_dados_coleta_id'), 'dados_coleta', ['id'], unique=False)
    op.create_table('metodologias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=True),
    sa.Column('desc_numerador', sa.Text(), nullable=True),
    sa.Column('desc_denominador', sa.Text(), nullable=True),
    sa.Column('multiplicador', sa.Float(), nullable=True),
    sa.Column('unidade_medida', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodologias_id'), 'metodologias', ['id'], unique=False)
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dados_coleta_id', sa.Integer(), nullable=True),
    sa.Column('fonte_nome', sa.String(), nullable=True),
    sa.Column('fonte_url', sa.String(), nullable=True),
    sa.Column('data_extracao', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dados_coleta_id'], ['dados_coleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorias_id'), 'auditorias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditorias_id'), table_name='auditorias')
    op.drop_table('auditorias')
    op.drop_index(op.f('ix_metodologias_id'), table_name='metodologias')
    op.drop_table('metodologias')
    op.drop_index(op.f('ix_dados_coleta_id'), table_name='dados_coleta')
    op.drop_index(op.f('ix_dados_coleta_cidade'), table_name='dados_coleta')
    op.drop_table('dados_coleta')
    op.drop_index(op.f('ix_indicadores_id'), table_name='indicadores')
    op.drop_index(op.f('ix_indicadores_codigo_indicador'), table_name='indicadores')
    op.drop_table('indicadores')
    # ### end Alembic commands ###
